package:
  name: telegrapi
  version: "0.0.4"

source:
  path: ./telegrapi/

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
     - python
     - pip
     - setuptools
  run:
     - python